services:
  web:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"   # better file watching on Win/macOS
    command: sh -c "npm ci && npm run dev -- --host --port 5173"