version: '3.8'

services:
  mongodb:
    image: mongo:7
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    image: movie-booking-backend:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - network
    expose:
      - "5000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
      args:
        VITE_BASE_URL: /api
    image: movie-booking-frontend:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - network

volumes:
  mongodb_data:
    name: movie-booking-mongodb-data

networks:
  network:
    driver: bridge
