version: '3.8'

services:
  mongodb:
    image: mongo:7
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - network

  backend:
    image: yohan2001/online_movie_ticket_booking_system-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - network

  frontend:
    image: yohan2001/online_movie_ticket_booking_system-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:80" 
    depends_on:
      - backend
    networks:
      - network

volumes:
  mongodb_data:
    name: movie-booking-mongodb-data

networks:
  network:
    driver: bridge