version: "3.8"

services:
  dind:
    image: docker:24-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - jenkins_docker:/var/lib/docker

  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - DOCKER_TLS_CERTDIR=
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - dind

volumes:
  jenkins_home:
  jenkins_docker:
