version: "3.9"
services:
 frontend:
   build:
     context: ./client
     dockerfile: Dockerfile
   container_name: client
   restart: always
   ports:
     - 3000:3000
   volumes:
     - ./client:/app
     - /app/node_modules
   environment:
     - VITE_APP_BACKEND_ADDRESS=http://localhost/api
   networks:
     - network
networks:
 network: